export const INVENTORY = {
  Vapes: [
    {
      name: "GeekBar Pulse 15k",
      brand: "GeekBar",
      price: "$24.99",
      flavor: "Fabulous Fab",
      tag: "Best Seller",
      image: "/assets/products/geekbar-pulse-15k.svg",
      imageAlt: "GeekBar Pulse 15k disposable vape in Fabulous Fab flavor",
      imageWidth: 1200,
      imageHeight: 800,
      imageSizes: "(min-width: 1024px) 33vw, (min-width: 640px) 50vw, 100vw",
      imageLoading: "lazy",
      imageCredit: "DS Smoke Vapor"
    },
    {
      name: "Lost Mary MT15000",
      brand: "Lost Mary",
      price: "$23.99",
      flavor: "Nana Coconut",
      tag: "New",
      image: "/assets/products/lost-mary-mt15000.svg",
      imageAlt: "Lost Mary MT15000 vape with Nana Coconut flavor",
      imageWidth: 1200,
      imageHeight: 800,
      imageSizes: "(min-width: 1024px) 33vw, (min-width: 640px) 50vw, 100vw",
      imageLoading: "lazy",
      imageCredit: "DS Smoke Vapor"
    },
    {
      name: "Raz TN9000",
      brand: "Raz",
      price: "$21.99",
      flavor: "Dragon Fruit",
      tag: "Hot",
      image: "/assets/products/raz-tn9000.svg",
      imageAlt: "Raz TN9000 disposable vape with Dragon Fruit flavor",
      imageWidth: 1200,
      imageHeight: 800,
      imageSizes: "(min-width: 1024px) 33vw, (min-width: 640px) 50vw, 100vw",
      imageLoading: "lazy",
      imageCredit: "DS Smoke Vapor"
    },
    {
      name: "North 12000",
      brand: "North",
      price: "$19.99",
      flavor: "Cactus Chill",
      tag: "",
      image: "/assets/products/north-12000.svg",
      imageAlt: "North 12000 vape in Cactus Chill",
      imageWidth: 1200,
      imageHeight: 800,
      imageSizes: "(min-width: 1024px) 33vw, (min-width: 640px) 50vw, 100vw",
      imageLoading: "lazy",
      imageCredit: "DS Smoke Vapor"
    },
    {
      name: "Tyson 2.0 Iron Mike",
      brand: "Tyson",
      price: "$22.99",
      flavor: "Frozen Grape",
      tag: "",
      image: "/assets/products/tyson-iron-mike.svg",
      imageAlt: "Tyson 2.0 Iron Mike vape in Frozen Grape",
      imageWidth: 1200,
      imageHeight: 800,
      imageSizes: "(min-width: 1024px) 33vw, (min-width: 640px) 50vw, 100vw",
      imageLoading: "lazy",
      imageCredit: "DS Smoke Vapor"
    },
    {
      name: "Fifty Bar",
      brand: "Fifty",
      price: "$18.99",
      flavor: "Milky Loops",
      tag: "USA Made",
      image: "/assets/products/fifty-bar.svg",
      imageAlt: "Fifty Bar disposable vape in Milky Loops",
      imageWidth: 1200,
      imageHeight: 800,
      imageSizes: "(min-width: 1024px) 33vw, (min-width: 640px) 50vw, 100vw",
      imageLoading: "lazy",
      imageCredit: "DS Smoke Vapor"
    },
    {
      name: "GeekBar Pulse X",
      brand: "GeekBar",
      price: "$25.99",
      flavor: "Sour Apple",
      tag: "New",
      image: "/assets/products/geekbar-pulse-x.svg",
      imageAlt: "GeekBar Pulse X vape in Sour Apple",
      imageWidth: 1200,
      imageHeight: 800,
      imageSizes: "(min-width: 1024px) 33vw, (min-width: 640px) 50vw, 100vw",
      imageLoading: "lazy",
      imageCredit: "DS Smoke Vapor"
    },
    {
      name: "Elf Bar BC5000",
      brand: "Elf Bar",
      price: "$16.99",
      flavor: "Watermelon Ice",
      tag: "Classic",
      image: "/assets/products/elf-bar-bc5000.svg",
      imageAlt: "Elf Bar BC5000 vape in Watermelon Ice",
      imageWidth: 1200,
      imageHeight: 800,
      imageSizes: "(min-width: 1024px) 33vw, (min-width: 640px) 50vw, 100vw",
      imageLoading: "lazy",
      imageCredit: "DS Smoke Vapor"
    }
  ],
  Glass: [
    {
      name: "Gravity Infuser",
      brand: "Stündenglass",
      price: "$599.00",
      flavor: "Black",
      tag: "Premium",
      image: "/assets/products/gravity-infuser.svg",
      imageAlt: "Stündenglass Gravity Infuser in black finish",
      imageWidth: 1200,
      imageHeight: 800,
      imageSizes: "(min-width: 1024px) 33vw, (min-width: 640px) 50vw, 100vw",
      imageLoading: "lazy",
      imageCredit: "DS Smoke Vapor"
    },
    {
      name: "Beaker Bong 12\"",
      brand: "Medicali",
      price: "$149.99",
      flavor: "Clear",
      tag: "Classic",
      image: "/assets/products/beaker-bong-12.svg",
      imageAlt: "Medicali 12 inch beaker bong in clear glass",
      imageWidth: 1200,
      imageHeight: 800,
      imageSizes: "(min-width: 1024px) 33vw, (min-width: 640px) 50vw, 100vw",
      imageLoading: "lazy",
      imageCredit: "DS Smoke Vapor"
    },
    {
      name: "Peak Pro",
      brand: "Puffco",
      price: "$420.00",
      flavor: "Pearl",
      tag: "Tech",
      image: "/assets/products/peak-pro.svg",
      imageAlt: "Puffco Peak Pro device in pearl color",
      imageWidth: 1200,
      imageHeight: 800,
      imageSizes: "(min-width: 1024px) 33vw, (min-width: 640px) 50vw, 100vw",
      imageLoading: "lazy",
      imageCredit: "DS Smoke Vapor"
    },
    {
      name: "Carta 2",
      brand: "Focus V",
      price: "$350.00",
      flavor: "Midnight",
      tag: "",
      image: "/assets/products/carta-2.svg",
      imageAlt: "Focus V Carta 2 in midnight finish",
      imageWidth: 1200,
      imageHeight: 800,
      imageSizes: "(min-width: 1024px) 33vw, (min-width: 640px) 50vw, 100vw",
      imageLoading: "lazy",
      imageCredit: "DS Smoke Vapor"
    },
    {
      name: "Hammer Bubbler",
      brand: "Grav",
      price: "$44.99",
      flavor: "Smoke",
      tag: "",
      image: "/assets/products/hammer-bubbler.svg",
      imageAlt: "Grav hammer bubbler in smoke color",
      imageWidth: 1200,
      imageHeight: 800,
      imageSizes: "(min-width: 1024px) 33vw, (min-width: 640px) 50vw, 100vw",
      imageLoading: "lazy",
      imageCredit: "DS Smoke Vapor"
    },
    {
      name: "Mini Rig",
      brand: "MJ Arsenal",
      price: "$69.99",
      flavor: "Claude",
      tag: "",
      image: "/assets/products/mini-rig.svg",
      imageAlt: "MJ Arsenal mini rig in Claude style",
      imageWidth: 1200,
      imageHeight: 800,
      imageSizes: "(min-width: 1024px) 33vw, (min-width: 640px) 50vw, 100vw",
      imageLoading: "lazy",
      imageCredit: "DS Smoke Vapor"
    },
    {
      name: "Straight Tube",
      brand: "Roor",
      price: "$320.00",
      flavor: "18 inch",
      tag: "German Glass",
      image: "/assets/products/straight-tube.svg",
      imageAlt: "Roor 18 inch straight tube glass piece",
      imageWidth: 1200,
      imageHeight: 800,
      imageSizes: "(min-width: 1024px) 33vw, (min-width: 640px) 50vw, 100vw",
      imageLoading: "lazy",
      imageCredit: "DS Smoke Vapor"
    },
    {
      name: "Ash Catcher",
      brand: "Pulsar",
      price: "$35.00",
      flavor: "14mm 45deg",
      tag: "",
      image: "/assets/products/ash-catcher.svg",
      imageAlt: "Pulsar 14mm 45 degree ash catcher",
      imageWidth: 1200,
      imageHeight: 800,
      imageSizes: "(min-width: 1024px) 33vw, (min-width: 640px) 50vw, 100vw",
      imageLoading: "lazy",
      imageCredit: "DS Smoke Vapor"
    }
  ],
  "THC-A / Delta": [
    {
      name: "Haymaker Blend",
      brand: "Torch",
      price: "$34.99",
      flavor: "3.5g Disposable",
      tag: "Potent",
      image: "/assets/products/haymaker-blend.svg",
      imageAlt: "Torch Haymaker Blend 3.5g disposable",
      imageWidth: 1200,
      imageHeight: 800,
      imageSizes: "(min-width: 1024px) 33vw, (min-width: 640px) 50vw, 100vw",
      imageLoading: "lazy",
      imageCredit: "DS Smoke Vapor"
    },
    {
      name: "Wrecked Gummies",
      brand: "Looper",
      price: "$29.99",
      flavor: "Sour Belts",
      tag: "Edible",
      image: "/assets/products/wrecked-gummies.svg",
      imageAlt: "Looper Wrecked Gummies sour belts",
      imageWidth: 1200,
      imageHeight: 800,
      imageSizes: "(min-width: 1024px) 33vw, (min-width: 640px) 50vw, 100vw",
      imageLoading: "lazy",
      imageCredit: "DS Smoke Vapor"
    },
    {
      name: "Liquid Badder",
      brand: "Urb",
      price: "$32.99",
      flavor: "Funky Monkey",
      tag: "",
      image: "/assets/products/liquid-badder.svg",
      imageAlt: "Urb Liquid Badder in Funky Monkey",
      imageWidth: 1200,
      imageHeight: 800,
      imageSizes: "(min-width: 1024px) 33vw, (min-width: 640px) 50vw, 100vw",
      imageLoading: "lazy",
      imageCredit: "DS Smoke Vapor"
    },
    {
      name: "Snowballs",
      brand: "ElfTHC",
      price: "$45.99",
      flavor: "3.5g Flower",
      tag: "Top Shelf",
      image: "/assets/products/snowballs.svg",
      imageAlt: "ElfTHC Snowballs 3.5g flower",
      imageWidth: 1200,
      imageHeight: 800,
      imageSizes: "(min-width: 1024px) 33vw, (min-width: 640px) 50vw, 100vw",
      imageLoading: "lazy",
      imageCredit: "DS Smoke Vapor"
    },
    {
      name: "Adios Blend",
      brand: "Exodus",
      price: "$39.99",
      flavor: "7g Disposable",
      tag: "Huge",
      image: "/assets/products/adios-blend.svg",
      imageAlt: "Exodus Adios Blend 7g disposable",
      imageWidth: 1200,
      imageHeight: 800,
      imageSizes: "(min-width: 1024px) 33vw, (min-width: 640px) 50vw, 100vw",
      imageLoading: "lazy",
      imageCredit: "DS Smoke Vapor"
    },
    {
      name: "Mushroom Gummies",
      brand: "Tre House",
      price: "$24.99",
      flavor: "Magic Mango",
      tag: "Nootropic",
      image: "/assets/products/mushroom-gummies.svg",
      imageAlt: "Tre House mushroom gummies in Magic Mango",
      imageWidth: 1200,
      imageHeight: 800,
      imageSizes: "(min-width: 1024px) 33vw, (min-width: 640px) 50vw, 100vw",
      imageLoading: "lazy",
      imageCredit: "DS Smoke Vapor"
    },
    {
      name: "Pre-Rolls 5pk",
      brand: "Cutleaf",
      price: "$25.99",
      flavor: "Gelato",
      tag: "",
      image: "/assets/products/pre-rolls-5pk.svg",
      imageAlt: "Cutleaf Gelato pre-rolls five pack",
      imageWidth: 1200,
      imageHeight: 800,
      imageSizes: "(min-width: 1024px) 33vw, (min-width: 640px) 50vw, 100vw",
      imageLoading: "lazy",
      imageCredit: "DS Smoke Vapor"
    },
    {
      name: "Delta 9 Syrup",
      brand: "Enjoy",
      price: "$19.99",
      flavor: "Blue Razz",
      tag: "Liquid",
      image: "/assets/products/delta-9-syrup.svg",
      imageAlt: "Enjoy Delta 9 syrup in Blue Razz flavor",
      imageWidth: 1200,
      imageHeight: 800,
      imageSizes: "(min-width: 1024px) 33vw, (min-width: 640px) 50vw, 100vw",
      imageLoading: "lazy",
      imageCredit: "DS Smoke Vapor"
    }
  ],
  Accessories: [
    {
      name: "Classic Papers",
      brand: "Raw",
      price: "$2.99",
      flavor: "King Size",
      tag: "Essential",
      image: "/assets/products/classic-papers.svg",
      imageAlt: "Raw classic king size rolling papers",
      imageWidth: 1200,
      imageHeight: 800,
      imageSizes: "(min-width: 1024px) 33vw, (min-width: 640px) 50vw, 100vw",
      imageLoading: "lazy",
      imageCredit: "DS Smoke Vapor"
    },
    {
      name: "Grinder 63mm",
      brand: "Santa Cruz",
      price: "$24.99",
      flavor: "Purple",
      tag: "Durable",
      image: "/assets/products/grinder-63mm.svg",
      imageAlt: "Santa Cruz 63mm grinder in purple",
      imageWidth: 1200,
      imageHeight: 800,
      imageSizes: "(min-width: 1024px) 33vw, (min-width: 640px) 50vw, 100vw",
      imageLoading: "lazy",
      imageCredit: "DS Smoke Vapor"
    },
    {
      name: "Butane Torch",
      brand: "Blazer",
      price: "$59.99",
      flavor: "Big Shot",
      tag: "Tools",
      image: "/assets/products/butane-torch.svg",
      imageAlt: "Blazer Big Shot butane torch",
      imageWidth: 1200,
      imageHeight: 800,
      imageSizes: "(min-width: 1024px) 33vw, (min-width: 640px) 50vw, 100vw",
      imageLoading: "lazy",
      imageCredit: "DS Smoke Vapor"
    },
    {
      name: "Rolling Tray",
      brand: "Cookies",
      price: "$14.99",
      flavor: "Red V2",
      tag: "",
      image: "/assets/products/rolling-tray.svg",
      imageAlt: "Cookies rolling tray in Red V2",
      imageWidth: 1200,
      imageHeight: 800,
      imageSizes: "(min-width: 1024px) 33vw, (min-width: 640px) 50vw, 100vw",
      imageLoading: "lazy",
      imageCredit: "DS Smoke Vapor"
    },
    {
      name: "Odor Spray",
      brand: "Ozium",
      price: "$6.99",
      flavor: "Original",
      tag: "",
      image: "/assets/products/odor-spray.svg",
      imageAlt: "Ozium odor spray in original scent",
      imageWidth: 1200,
      imageHeight: 800,
      imageSizes: "(min-width: 1024px) 33vw, (min-width: 640px) 50vw, 100vw",
      imageLoading: "lazy",
      imageCredit: "DS Smoke Vapor"
    },
    {
      name: "Quartz Banger",
      brand: "Bear Quartz",
      price: "$29.99",
      flavor: "14mm Male",
      tag: "",
      image: "/assets/products/quartz-banger.svg",
      imageAlt: "Bear Quartz 14mm male quartz banger",
      imageWidth: 1200,
      imageHeight: 800,
      imageSizes: "(min-width: 1024px) 33vw, (min-width: 640px) 50vw, 100vw",
      imageLoading: "lazy",
      imageCredit: "DS Smoke Vapor"
    },
    {
      name: "Iso Stations",
      brand: "Glob Mops",
      price: "$15.99",
      flavor: "Cotton Swabs",
      tag: "Cleaning",
      image: "/assets/products/iso-stations.svg",
      imageAlt: "Glob Mops iso stations cotton swabs",
      imageWidth: 1200,
      imageHeight: 800,
      imageSizes: "(min-width: 1024px) 33vw, (min-width: 640px) 50vw, 100vw",
      imageLoading: "lazy",
      imageCredit: "DS Smoke Vapor"
    },
    {
      name: "Lighter Leash",
      brand: "Generic",
      price: "$3.99",
      flavor: "Black",
      tag: "Handy",
      image: "/assets/products/lighter-leash.svg",
      imageAlt: "Black lighter leash accessory",
      imageWidth: 1200,
      imageHeight: 800,
      imageSizes: "(min-width: 1024px) 33vw, (min-width: 640px) 50vw, 100vw",
      imageLoading: "lazy",
      imageCredit: "DS Smoke Vapor"
    }
  ]
};

export const PRICE_RANGES = [
  { label: "Under $20", min: 0, max: 20 },
  { label: "$20 - $50", min: 20, max: 50 },
  { label: "$50 - $100", min: 50, max: 100 },
  { label: "$100+", min: 100, max: Infinity }
];

export const parsePrice = (priceStr) => parseFloat(priceStr.replace(/[^0-9.]/g, ''));
